### PR TITLE
V2ray-plugin Websocket 0-RTT fix

### PR DESCRIPTION
**Pull request by sqwwqw5**
The same issue I fixed yesterday with Xray-plugin.
https://github.com/teddysun/xray-plugin/commit/cc2df0f46bf7607bad159878497b19acf83bc6a6
https://github.com/MetaCubeX/Clash.Meta/issues/224#issuecomment-1501284300
Before:
image
Afer:
image

Feel free to tidy it up after the commit.

### CODE REVIEW

**Comment by wwqgtxx** [comment]
我不知道你是如何得出延迟会降低的结论的，你增加的这段代码和现有代码中`NewV2rayObfs`会调用的`vmess.StreamWebsocketConn`并没有什么区别
https://github.com/MetaCubeX/Clash.Meta/blob/4d12ed491cd23c99a56d61961640b6f2c40b9794/transport/vmess/websocket.go#L412-L430

**Comment by sqwwqw5** [comment]
> 我不知道你是如何得出延迟会降低的结论的，你增加的这段代码和现有代码中`NewV2rayObfs`会调用的`vmess.StreamWebsocketConn`并没有什么区别
> 
> https://github.com/MetaCubeX/Clash.Meta/blob/4d12ed491cd23c99a56d61961640b6f2c40b9794/transport/vmess/websocket.go#L412-L430

Build it yourself and see for yourself.

**Comment by wwqgtxx** [comment]
在我本地的测试中两者没有任何的区别，你修改之前的测试是基于最新的alpha版本测试的么

**Comment by sqwwqw5** [comment]
> 在我本地的测试中两者没有任何的区别，你修改之前的测试是基于最新的alpha版本测试的么

The one comes with the v2rayN which I believe is relatively new. Both Clash and Meta exhibit the same issue.
I'm just an end user.

**Comment by sqwwqw5** [comment]
> 在我本地的测试中两者没有任何的区别，你修改之前的测试是基于最新的alpha版本测试的么

I will build a new one with the alpha release to see if anything is different.

**Comment by sqwwqw5** [comment]
> 在我本地的测试中两者没有任何的区别，你修改之前的测试是基于最新的alpha版本测试的么

It turns out the latest alpha doesn't have this behavior, I got misled by all the information gathered in a short time, especially after the fix does work in the case of Xray-plugin, my apologies. It does mean that I will have a working client for another two or three years then, I'd rather not deal with the code and leave it up to the professions,  keep it up.

**Comment by wwqgtxx** [comment]
关于meta这边对ws0rtt的修复改动主要在如下三个commit中
https://github.com/MetaCubeX/Clash.Meta/commit/75680c5866ebc497016120cda9afc39c3e13a0aa
https://github.com/MetaCubeX/Clash.Meta/commit/c1199f1a8abc3088a8330cce50232e2ed6edff02
https://github.com/MetaCubeX/Clash.Meta/commit/5816dc295517528dae6b7902114efd552509dd5a
最终生效的版本是v1.14.3，所以你测试所用的ClashN集成的版本可能不够新导致了错误的结论
此外该项修复以及你发给xray-plugin的PR均并不适用于原版的clash，所以建议你关闭那边的issue毕竟造成误导

**Comment by sqwwqw5** [comment]
> 关于meta这边对ws0rtt的修复改动主要在如下三个commit中 [75680c5](https://github.com/MetaCubeX/Clash.Meta/commit/75680c5866ebc497016120cda9afc39c3e13a0aa) [c1199f1](https://github.com/MetaCubeX/Clash.Meta/commit/c1199f1a8abc3088a8330cce50232e2ed6edff02) [5816dc2](https://github.com/MetaCubeX/Clash.Meta/commit/5816dc295517528dae6b7902114efd552509dd5a) 最终生效的版本是v1.14.3，所以你测试所用的ClashN集成的版本可能不够新导致了错误的结论 此外该项修复以及你发给xray-plugin的PR均并不适用于原版的clash，所以建议你关闭那边的issue避免造成误导

I will spend some time to learn how thoose commits actually made things work, it fascinates me and yes, Clash's latest release also has the issue fixed already. It boggles me when I heard this feature very recently that released two years ago doesn't work on all major clients, things must be much more difficulte under the hood.

**Pull request closed without merging**
