### PR TITLE
fix: baidu direct connect

### PR DESCRIPTION
**Pull request by XLXNG**
#534 fix：change "type: http" to "type: bdzl"

### CODE REVIEW

**Comment by H1JK** [comment]
Please briefly describe this PR.

This looks like making another HTTP outbound. So why not just work on the HTTP type?

**Comment by XLXNG** [comment]
The request header is not a standard HTTP request header. example: "CONNECT addrHTTP/1.1"

**Comment by Skyxim** [comment]
If you only modify the host field, you only need to modify the http agent's handling of the host field.

**Comment by XLXNG** [comment]
There is this problem in #534 ,but the problem isn't what #534 described

**Comment by Skyxim** [comment]
The `Host` field cannot be overwritten directly by http header in go.

But you just need to simply assign a value to `Request#Hodt`, and there is no need to process it manually.

**Pull request closed without merging**
