### PR TITLE
feat: bump restls to v0.1.5 (utls v1.4.3)

### PR DESCRIPTION
**Pull request by 3andne**
Hi,
Sorry for the delay. We were working on this update throughout the entire week. 
Off topic:
It turns out we were among the few projects leveraging session resumption (we don't rebuild the TLS Config per connection). This led us down many rarely traversed paths, which hadn't been tested for years. Pinpointing and resolving these issues was time-consuming.  
Our efforts culminated in the introduction of a long-awaited feature in uTLS: PSK-based session resumption for TLS 1.3. We're in the final stages of our work, anticipating its integration into uTLS. Implementing the PSK feature will enhance parroting, aligning utls clients more closely with browsers, especially given that recent Chrome versions utilize PSK-based sessions for TLS 1.3.

### CODE REVIEW

**Comment by wwqgtxx** [comment]
Please do not import `quic-go/quic-go` in dependencies.

**Comment by 3andne** [comment]
> Please do not import `quic-go/quic-go` in dependencies.

The module `quic-go` is introduced by utls v1.4.0. It will probably be there anyways if you bump the version of utls. I'm not sure about the best practices here. Any recommendations or guidance?

**Comment by wwqgtxx** [comment]
> > Please do not import `quic-go/quic-go` in dependencies.
> 
> The module `quic-go` is introduced by utls v1.4.0. It will probably be there anyways if you bump the version of utls. I'm not sure about the best practices here. Any recommendations or guidance?

I took a look at the code. In fact, only `quicvarint` is used in `u_quic_transport_parameters.go`, so you can easily place `quicvarint` inside the `restls-client-go` project (https://github.com/quic-go/quic-go/blob/master/quicvarint/varint.go), which removes the dependency on `quic-go`.

**Comment by wwqgtxx** [comment]
maybe you can merge https://github.com/3andne/restls-client-go/pull/4

**Comment by 3andne** [comment]
> maybe you can merge https://github.com/3andne/restls-client-go/pull/4

Wow, nice work. Sorry I didn't see that, but thanks anyways. I have updated and remove the `go-quic` dependency.

**Pull request merged**
