### PR TITLE
[Feature] Proxy stores delay data of different URLs. And supports specifying different test URLs and expected statue by group

### PR DESCRIPTION
**Pull request by wzdnzd**
Each proxy corresponds to a different testUrl with varying latency and status. Storing the latency under different test URLs for different groups is meaningful. Meanwhile, different proxy groups can specify the expected status during latency testing and health checks.

> To reduce memory usage and speed up health checks, in addition to the URL test specified by the proxy provider, a maximum of 6 additional test URLs are supported.

> For memory safety reasons (to prevent memory exhaustion caused by testing latency and health checks with a large number of different test URLs), delay data generated by external controllers is not stored by default. This can be modified to save a limited amount of URL delay data.

> If this feature is accepted, I will refactor the Proxy interface code and modify the original Alive method and DelayHistory method again.

### CODE REVIEW

**Comment by Skyxim** [comment]
The node state is held by each individual, while the strategy group shares its state. I haven't seen you separate them. If they are separated, how can we avoid unnecessary testing for users who don't require different settings?

**Comment by wzdnzd** [comment]
> The node state is held by each individual, while the strategy group shares its state. I haven't seen you separate them. If they are separated, how can we avoid unnecessary testing for users who don't require different settings?

+ In the [healthcheck struct](https://github.com/MetaCubeX/Clash.Meta/blob/a0e5ff1f08164415a00a622af655cf3bf56a0c9d/adapter/provider/healthcheck.go#L35), I added an extra attribute which is a map with test URLs as keys and regular expressions and expected states as values. The regular expressions are used to filter the actual proxies that need to be tested by groups registered in the provider.

+ When parsing the proxy provider, the configured health check URL is saved in the "url" field of "hc". When parsing the proxy group, a new provider will be created for proxies and its corresponding hc's URL will be an empty string.

+ Both the test URL, expected status and filtering regex in both proxies and use correspond to the provider, which will [register](https://github.com/MetaCubeX/Clash.Meta/blob/a0e5ff1f08164415a00a622af655cf3bf56a0c9d/adapter/outboundgroup/parser.go#L112) them into the extra of hc held by the provider. The regex is a set, with different regex for the same test URL ultimately concatenated by "|". Through [this method](https://github.com/MetaCubeX/Clash.Meta/blob/a0e5ff1f08164415a00a622af655cf3bf56a0c9d/adapter/provider/healthcheck.go#L75), it is possible to achieve testing only once for the same test URL. And only those proxies that are additionally configured in the proxy group will be tested.

+ During the health check, not only the URL of HC is tested, but also the URLs registered in "extra" are tested. [code](https://github.com/MetaCubeX/Clash.Meta/blob/a0e5ff1f08164415a00a622af655cf3bf56a0c9d/adapter/provider/healthcheck.go#L158)

+ In the proxy, the original history storage provider stores default configuration latency data. An extra attribute (a map with URL as key and delay data queue as value) has been added to [store data](https://github.com/MetaCubeX/Clash.Meta/blob/a0e5ff1f08164415a00a622af655cf3bf56a0c9d/adapter/adapter.go#L200) for test URLs registered by groups.

+ The reason for storing separately instead of merging is that the proxy provider represents the real status of the node, while the data in extra may contain conditional states registered by the proxy group.

**Comment by wwqgtxx** [comment]
Is the ProxyProvider missing in the setting of `expected-status`?

**Comment by wzdnzd** [comment]
> Is the ProxyProvider missing in the setting of `expected-status`?

I was initially supportive, but later I felt that the health check status represented the most authentic state of the proxy in ProxyProvider. The expected-status is an additional condition attached to GroupProxy. Therefore, it was later removed by me. If necessary, I can add it again.

**Comment by wwqgtxx** [comment]
> > Is the ProxyProvider missing in the setting of `expected-status`?
> 
> I was initially supportive, but later I felt that the health check status represented the most authentic state of the proxy in ProxyProvider. The expected-status is an additional condition attached to GroupProxy. Therefore, it was later removed by me. If necessary, I can add it again.

I think it is better to add it and let users choose whether to use it.

**Comment by wzdnzd** [comment]
Okay, I'll submit a PR when I'm free.

**Pull request merged**
